### ISSUE TITLE
Update version of github.com/evanphx/json-patch

### ISSUE THREAD

**Issue by mknycha** [hashicorp/go-discover#160]
Hi, it looks like there is a vulnerability in one of your dependencies: github.com/evanphx/json-patch v4.2.0
### Description:
This issue was discovered in the context of an out-of-bound write that occurred when patching an Openshift object using the 'oc patch' functionality.

### Link:
https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-14632

It looks like it can be fixed by upgrading to version >= 4.4.0.

**Comment by dnephin** [comment]
Hello, thank you for the report.

From what I can see, this repository does not use that json-patch library. The library does appear in its `go.sum` file, because it happens to be in the `go.sum` for https://github.com/kubernetes/apimachinery, but it's not used by any of the packages. If you run `go mod vendor` you'll see that the `json-patch` library does not end up in vendor.

**Comment by mknycha** [comment]
Oops, my bad
