### ISSUE TITLE
Segment ports with Cloud Auto-Join?

### ISSUE THREAD

**Issue by ashald** [hashicorp/go-discover#57]
From documentation it seems that it's impossible to use Cloud Auto-Join with network segments feature that requires connecting on different port numbers.

Either documentation need to be clarified or feature to be added. :)

**Comment by sbasyal** [comment]
I agree with you that there is a Documentation gap here, that we can improve.

When you are using Cloud Auto-join with Network Segments, you have to make sure the segment port matches on client and server. You would want to set the [serf_lan](https://www.consul.io/docs/agent/options.html#serf_lan_bind) port of the clients to the segment port you're going to join on the servers. By default, the clients try to join on `8301` - that's because they default to trying to join on their own `serf_lan` port.
So, on the clients, you have to set your `serf_lan` port to whatever segment you're joining. 

For example, if you have the following segments and use Cloud Auto-Join, then you have to set your `serf_lan` port to `8311` or `8321` depending upon which segment you want to join.

``` 
"segments": [ 
	{"name": "foo", "bind": "{{GetPrivateIP}}", "advertise": "{{GetPrivateIP}}", "port": 8331}, 
	{"name": "bar", "bind": "{{GetPrivateIP}}", "advertise": "{{GetPrivateIP}}", "port": 8341} 
]
```

**Comment by Ashald** [comment]
Yeah, that's exactly what I did eventually. But besides this not being documented, I also feel that it's very confusing that there are several ways to do the same thing that overlap a bit. As in:
1) You can set `serf_lan` and then join by a domain name or IP
2) You join by a domain name or IP with port without setting `serf_lan`
3) With cloud auto-join you can do only (1) but not (2)

IMO, ideally it should be a consistent:
1) Either require port to be specified via serf_lan at all times
2) or allow port to be specified in go-discover config
