### ISSUE TITLE
DigitalOcean: Use only private ip?

### ISSUE THREAD

**Issue by webchi** [hashicorp/go-discover#64]
Why we are using only private ip here? https://github.com/hashicorp/go-discover/blob/master/provider/digitalocean/digitalocean_discover.go#L107
Maybe use public also?

**Comment by webchi** [comment]
Autojoin on digitalocean becomes completly unusefull with private ip searching if I want to connect nodes from different regions. Because those nodes will have ips in different subnets and shall be unreachable.

**Comment by lfarnell** [comment]
@webchi DigitalOcean is unique in this case because it doesn't offer availability zones or a similar construct. Consul's concept of a datacenter is as follow's:

> We define a datacenter to be a networking environment that is private, low latency, and high bandwidth.

If you wanted to run Consul servers over the public IP then I suggest that you use the public IP addresses and forgo the use of auto-discovery. This is just a limitation of DigitalOcean and not Consul. I would also  advise you **_NOT_** to run Consul servers in different regions as you will see performance issues due to the higher latency. Your best bet would be to run all Consul servers in the same region and if you needed multi-region support to use the federation functionality.

**Comment by webchi** [comment]
Thanks. I've realized that we don't really need consul in our configuration. This is another tool.
